### ISSUE TITLE
Current month used issue / Sollentuna Energi (Sweden), Kamstrup Omnipower

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#861] opened 2024-10-29 09:22 UTC
### Discussed in https://github.com/UtilitechAS/amsreader-firmware/discussions/843

There is a known issue that appears on Kamstrup Omnipower meters at Sollentuna Energi, Sweden.

A fix that resolves the issue is published here: https://github.com/UtilitechAS/amsreader-firmware/discussions/843#discussioncomment-10714532

The fix will be included in upcoming firmware v2.3.9.

We'll keep this thread open until v2.3.9 is released.

**Comment by gskjold** [comment] 2024-11-03 09:36
Duplicate of #844

**Closed by gskjold** 2024-11-03 09:36 UTC
Labels: bug
