### ISSUE TITLE
HASS: Expose an update sensor

### ISSUE THREAD

**Issue by LordMike** [UtilitechAS/amsreader-firmware#634] opened 2023-09-11 17:19 UTC
**Is your feature request related to a problem? Please describe.**
I was following up on updating devices and realized that the amsleser may not have exposed an update sensor yet. 

It’s be great if it were, so Home Assistant can notify me in turn. 

I’m not sure if this firmware knows updates are available unless a user opens the page, but if it does, you could expose it. 

**Describe the solution you'd like**
An implementation that exposes an update sensor. 

https://www.home-assistant.io/integrations/update.mqtt/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pvarlien** [comment] 2023-10-23 08:32
Isn't this a duplicate of issue #263?

**Comment by gskjold** [comment] 2023-11-18 08:36
Correct

**Closed by gskjold** 2023-11-18 08:36 UTC
