### ISSUE TITLE
1 hour offset between HA and device

### ISSUE THREAD

**Issue by joachimtingvold** [UtilitechAS/amsreader-firmware#394] opened 2022-12-29 00:09 UTC
**Describe your problem**
Energy usage is offset by 1 hour when comparing HA with AmsToMqttBridge website. 22-23 on device becomes 23-00 in HA, 23-00 on device becomes 00-01 in HA, etc. All clocks seems to be the same, and all timezone settings seems to be correct as well.

I assume the "Summertime offset = +1hr" setting is automatic? (i.e. when set to "+1hr" it will add/remove 1 hour depending on wether or not its summertime, without having to manually do something).

Maybe I'm missing something really obvious here? Or? This might be an issue with HA itself, but yeah.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/359918/209886717-d78295e5-a1a1-4317-82aa-daeea368c13f.png">
<img width="561" alt="image" src="https://user-images.githubusercontent.com/359918/209886748-52e547c4-4f6f-4e0c-a9a5-136ee14286fe.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/359918/209886776-5ccb7ae5-c6dd-4ec3-87ad-2c8645cd22a0.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/359918/209886786-92add18b-0888-447f-833b-ef912761c5a3.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/359918/209886806-861b2637-ef05-45c4-96ac-50750332079f.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/359918/209886963-c72f613d-fc7c-407b-b925-5a3f00a67068.png">

**Hardware information:**
 - Country: Norway
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-K+
 - M-bus adapter (if applicable): N/A

**Relevant firmware information:**
 - Version: 2.1.16
 - MQTT: yes
 - MQTT payload type: Home Assistant
 - HAN GPIO: GPIO16
 - HAN baud and parity: 2400 8N1
 - Temperature sensors: N/A
 - ENTSO-E API enabled: N/A

**Comment by ArnieO** [comment] 2022-12-29 08:08
Interesting. 
At first glance this looks like an HA integration issue, but we have quite many HA users so it is surprising if this has not been spotted by others. (I don't use HA, so I cannot check/verify)

**Other HA users: Do you see the issue, or have an idea what could be the problem?**

Yes, summertime is automatic and works the way you describe.

Maybe related:
I have had a similar issue on my RasPi that runs Octopi/OctoPrint, where the GUI showed correct time but the calculation of end of print was 1 hour off. Please see if you can find a helpful hint here: https://community.octoprint.org/t/wrong-time-in-the-browsers-tab-title/29373/2

**Comment by kjetilrong** [comment] 2023-01-01 13:40
Same issue here.  "AMS reader v2.1.16",  Payload:Home-Assistant,  og Home Assistant 2022.12.8

![Screenshot from 2023-01-01 13-55-48](https://user-images.githubusercontent.com/6231894/210172461-a4d61a99-af93-4da8-98a5-cfbacc5aa2a4.png)
![Screenshot from 2023-01-01 13-55-25](https://user-images.githubusercontent.com/6231894/210172463-7d27b81a-cb36-463f-99b4-9dfeb576563b.png)

Could it have something to do with MQTT timestamp?

**Comment by bardahlm** [comment] 2023-01-01 21:11
This is an issue with HA. I belive it is caused by HA assigning the measurements to the hour it receives the measurment. And as the HAN port only outputs kWh once an hour (at 10 or so seconds past the hour) everything is offset in HA.

I've posted about this in the community forum but got no response: https://community.home-assistant.io/t/energy-one-hour-off/490506

The best fix would be if NVE revised their policy and got kWh meter readings posted more often.

**Comment by ArnieO** [comment] 2023-01-02 09:26
> This is an issue with HA. I belive it is caused by HA assigning the measurements to the hour it receives the measurment. And as the HAN port only outputs kWh once an hour (at 10 or so seconds past the hour) everything is offset in HA.

That makes sense. But are you sure it is a HA reception time issue - or could it be fixed by adjusting the timestamp coming from AmsToMqttBridge? If so, I guess it could be done in the HA MQTT payload generation for the cases where there is 1 hour (or more) since last payload. 

> The best fix would be if NVE revised their policy and got kWh meter readings posted more often.

Agree, but would imply changing firmware inn all AMS meters in Norway; I don't think it is realistic - and could create problem for other AMS meter readers running firmware that is less adaptive than this one.

**Comment by tronde-ams** [comment] 2023-01-02 16:07
Can it be possible to do some trickery with the realtime accumulated kWh instead for Home Assistant?

**Comment by bardahlm** [comment] 2023-01-02 17:23
> > This is an issue with HA. I belive it is caused by HA assigning the measurements to the hour it receives the measurment. And as the HAN port only outputs kWh once an hour (at 10 or so seconds past the hour) everything is offset in HA.
> 
> That makes sense. But are you sure it is a HA reception time issue - or could it be fixed by adjusting the timestamp coming from AmsToMqttBridge? If so, I guess it could be done in the HA MQTT payload generation for the cases where there is 1 hour (or more) since last payload.

I'm quite sure this is a HA issue. I'll try opening an issue for this.

**Comment by bardahlm** [comment] 2023-01-18 16:37
> I'll try opening an issue for this.

Can't really call this a success! I'll guess we'll have to come up with a PR to get this fixed and that is above my Python skills.

**Comment by kng** [comment] 2023-01-19 08:20
I looked at my meter (GMT+1) and it is accumulating correctly afaict, the past hour ~3.5kWh is correctly going to the graph.
Ticking over from 8:59-9:00 (not all the top row fields updated...)

![ams2](https://user-images.githubusercontent.com/5262110/213389239-8e1a0371-5f6a-491b-9afc-c13b47834915.png)

![ams3_ann](https://user-images.githubusercontent.com/5262110/213390014-1e23ebca-bb3b-4a00-807c-a183e380da85.png)

But the graph in HA doesn't show the last value but shifts it forward ?!

![ha3_ann](https://user-images.githubusercontent.com/5262110/213390040-196ecdd2-836c-4c3f-a0b8-d3fc2575d71c.png)

**Comment by joachimtingvold** [comment] 2023-01-19 14:29
> I looked at my meter (GMT+1) and it is accumulating correctly afaict, the past hour ~3.5kWh is correctly going to the graph.
> […]
> But the graph in HA doesn't show the last value but shifts it forward ?!

Yes, that is literally why this issue was created (shows correctly in AmsToMqttBridge, but 1 hour offset/delayed in HA).

**Closed** 2023-03-11 08:48 UTC
